- name: Create Azure VM
  hosts: localhost
  connection: local
                               
  vars_files:
    - ./vars.yml
  
  tasks:
    - name: Create MGMT public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ lane_rg }}"
        domain_name_label: "{{ vm_nameP }}"
        allocation_method: Static
        name: "{{ practice }}-{{ lane }}-panorama-mgmt-publicip"
        sku: Standard

    - name: Create management virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ lane_rg }}"
        name: "{{ practice }}-{{ lane }}-panorama-mgmt-nic"
        create_with_security_group: no
        virtual_network: "{{ practice }}-{{ lane }}-vnet"
        subnet: "{{ practice }}-{{ lane }}-mgmt-subnet"
        enable_ip_forwarding: yes
        ip_configurations:
          - name: ipcfg1
            private_ip_allocation_method: Dynamic
            public_ip_name: "{{ practice }}-{{ lane }}-panorama-mgmt-publicip"
            public_ip_allocation_method: Static
    - name: Create internal virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ lane_rg }}"
        name: "{{ practice }}-{{ lane }}-panorama-internal-nic"
        create_with_security_group: no      
        virtual_network: "{{ practice }}-{{ lane }}-vnet"
        subnet: "{{ practice }}-{{ lane }}-internal-subnet"
        enable_accelerated_networking: no
        enable_ip_forwarding: yes
        ip_configurations:
          - name: ipcfg3
            private_ip_allocation_method: Dynamic
    - name: "Create Panorama VM"
      azure_rm_virtualmachine:
        resource_group: "{{ lane_rg }}"
        boot_diagnostics:
          enabled: yes
        name: "{{ practice }}-{{ lane }}-Panorama"
        vm_size: Standard_D4s_v3
        admin_username: shi
        admin_password: 5ecur!ty_10I
        ssh_password_enabled: true
        started: no
        managed_disk_type: Standard_LRS
        network_interface_names:
          - "{{ practice }}-{{ lane }}-panorama-mgmt-nic"
          - "{{ practice }}-{{ lane }}-panorama-internal-nic"
        plan:
          name: "byol"
          product: "panorama"
          publisher: "paloaltonetworks"
        image:
          offer: "panorama"
          publisher: "paloaltonetworks"
          sku: "byol"
          version: "latest"        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
